# Describes the format of available services.

plasmawave_on:
  description: Turn on plasmawave.
  fields:
    entity_id:
      description: Name(s) of Winix entities. Leave service data empty to use all Winix entities.
      example: "fan.winix_living_room"

plasmawave_off:
  description: Turn off plasmawave.
  fields:
    entity_id:
      description: Name(s) of Winix entities. Leave service data empty to use all Winix entities.
      example: "fan.winix_living_room"

plasmawave_toggle:
  description: Toggle plasmawave.
  fields:
    entity_id:
      description: Name(s) of Winix entities. Leave service data empty to use all Winix entities.
      example: "fan.winix_living_room"

remove_stale_entities:
  description: Remove Winix entities with unavailable state and associated devices.
