restart_cloud_integrations:
  alias: "Restart Cloud Integrations"
  description: "Restart cloud integrations to resolve connection issues"
  icon: mdi:cloud-refresh
  sequence:
    - service: homeassistant.reload_config_entry
      target:
        device_id: 
          - "{{ device_id('Tuya') if device_id('Tuya') else none }}"
    - delay: "00:00:30"
    - service: system_log.write
      data:
        message: "Cloud integrations restarted due to connection issues"
        level: warning