esphome:
  name: atomecho
  friendly_name: AtomEcho

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "RUu0g63JzI8cldO0t97swPfFW/qPgSezFa5mV+X9SNA="

ota:
  - platform: esphome
    password: "a8913999e8de7251fec9309e9b698efe"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Atomecho Fallback Hotspot"
    password: "4QgygaXgpkQb"

captive_portal:
    