substitutions:
  name: home-assistant-voice-090900
  friendly_name: Home Assistant Voice 090900
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ro7N3g3txz/JzK/a86v0l98TjsxQeQ+Rrhk7jghU/7A=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password