esphome:
  name: waterlevelsensor2model3
  friendly_name: waterlevelsensor2model3

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+YXjmnxDqUL0rhKkZI6D+A2w2uf+yCy6xoSFho8/zks="

ota:
  - platform: esphome
    password: "c993496302fc3723b7dda6be2c91a725"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waterlevelsensor2Model3"
    password: "4FXINyctcrDw"

captive_portal:
one_wire:
  - platform: gpio
    pin: GPIO13    