esphome:
  name: bleproxy_with_lux
  friendly_name: bleproxy_with_lux

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  initial_level: ERROR
  logs:
    i2c: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "TR1oyfLMF35UEbOa42OKezXrPUBrdOnIXr10DDMVq0s="

ota:
  - platform: esphome
    password: "c7bd0eeffcf46d939be3c4cf2d0e3ae3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bleproxy Fallback Hotspot"
    password: "dwelaHXszU0q"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 320ms
    window: 30ms

bluetooth_proxy:

i2c:
  sda: GPIO10
  scl: GPIO9
  scan: True

sensor:
  - platform: bh1750
    name: "Light Level"
    update_interval: 120s # Increased update interval for testing
    unit_of_measurement: lx
    icon: "mdi:sun"

