blueprint:
  name: Dishwasher Cycle Finished Notification
  description: Sends a notification when your dishwasher cycle is complete based on power consumption.
  domain: automation
  input:
    power_sensor:
      name: Power Sensor
      description: The power consumption sensor for your dishwasher (in Watts).
      selector:
        entity:
          domain: sensor
          device_class: power
    idle_power_threshold:
      name: Idle Power Threshold
      description: The power level (in Watts) considered as "idle" (when the cycle is finished).
      default: 5
    duration_minutes:
      name: Duration
      description: The time (in minutes) the power must remain below the threshold to trigger the notification.
      default: 5
    notifier:
      name: Notifier
      description: The notification service to use (e.g., your mobile app).
      selector:
        entity:
          domain: notify
trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input idle_power_threshold
    for:
      minutes: !input duration_minutes
action:
  - service: !input notifier
    data:
      title: "Dishwasher Finished!"
      message: "The dishwasher cycle has completed."
