# Your Wi-Fi SSID and password
wifi_ssid: "Lakehouse"
wifi_password: "redflower805"
ota_password: "a44f3c1b4fdfb128c629d38403e16149"
ap_password: "redflower805"
api_encryption_key: "dsdH6Im7Pverxp6uu2DwyebaP/LwndSuIHM86gQ3tBo="
