# =============================================================================
# ENHANCED APPLIANCE INPUT HELPERS
# Additional input helpers needed for the enhanced appliance automation system
# =============================================================================

input_boolean:
  # Existing appliance cycle tracking booleans (preserve these)
  dishwasher_cycle_announced:
    name: "Dishwasher Cycle Announced"
    icon: mdi:dishwasher
  
  washing_machine_cycle_announced:
    name: "Washing Machine Cycle Announced"
    icon: mdi:washing-machine
  
  dryer_cycle_announced:
    name: "Dryer Cycle Announced"
    icon: mdi:tumble-dryer
  
  # Quiet hours control
  appliance_quiet_hours_enabled:
    name: "Appliance Quiet Hours Enabled"
    icon: mdi:sleep

input_datetime:
  # Enhanced cycle start time tracking
  dishwasher_cycle_start:
    name: "Dishwasher Cycle Start Time"
    has_date: true
    has_time: true
    icon: mdi:clock-start
  
  washing_machine_cycle_start:
    name: "Washing Machine Cycle Start Time"
    has_date: true
    has_time: true
    icon: mdi:clock-start
  
  dryer_cycle_start:
    name: "Dryer Cycle Start Time"
    has_date: true
    has_time: true
    icon: mdi:clock-start
  
  # Maintenance tracking
  dishwasher_last_filter_clean:
    name: "Dishwasher Last Filter Clean"
    has_date: true
    has_time: true
    icon: mdi:filter-variant
  
  washing_machine_last_hose_check:
    name: "Washing Machine Last Hose Check"
    has_date: true
    has_time: true
    icon: mdi:pipe

input_text:
  # Last announcement tracking
  appliance_last_announcement:
    name: "Last Appliance Announcement"
    max: 255
    icon: mdi:message-text

input_number:
  # Power consumption thresholds (configurable)
  dishwasher_start_threshold:
    name: "Dishwasher Start Threshold (Watts)"
    min: 20
    max: 200
    step: 5
    initial: 50
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt
  
  dishwasher_running_threshold:
    name: "Dishwasher Running Threshold (Watts)"
    min: 10
    max: 100
    step: 5
    initial: 30
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt
  
  dishwasher_stop_threshold:
    name: "Dishwasher Stop Threshold (Watts)"
    min: 1
    max: 50
    step: 1
    initial: 10
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline
  
  washing_machine_start_threshold:
    name: "Washing Machine Start Threshold (Watts)"
    min: 50
    max: 300
    step: 10
    initial: 100
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt
  
  washing_machine_running_threshold:
    name: "Washing Machine Running Threshold (Watts)"
    min: 20
    max: 150
    step: 5
    initial: 50
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt
  
  washing_machine_stop_threshold:
    name: "Washing Machine Stop Threshold (Watts)"
    min: 1
    max: 50
    step: 1
    initial: 15
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline

input_select:
  # Appliance state tracking
  dishwasher_state:
    name: "Dishwasher State"
    options:
      - "idle"
      - "starting"
      - "running"
      - "finishing"
      - "complete"
    initial: "idle"
    icon: mdi:dishwasher
  
  washing_machine_state:
    name: "Washing Machine State"
    options:
      - "idle"
      - "starting"
      - "running"
      - "finishing"
      - "complete"
    initial: "idle"
    icon: mdi:washing-machine
  
  dryer_state:
    name: "Dryer State"
    options:
      - "idle"
      - "starting"
      - "running"
      - "finishing"
      - "complete"
    initial: "idle"
    icon: mdi:tumble-dryer