# Smart Appliance Power Threshold System - Enhanced Input Numbers
# Multiple threshold levels for intelligent cycle phase detection

# =============================================================================
# EXISTING HYDROPONICS AND SYSTEM CONTROLS (PRESERVED)
# =============================================================================

hydroponics_fertigation_interval_hours:
  name: Fertigation Interval
  initial: 3
  min: 0
  max: 12
  step: 1
  mode: slider
  unit_of_measurement: hours
  icon: mdi:timer-outline

hydroponics_feed_pump_duration:
  name: Feed Pump Duration
  initial: 15
  min: 5
  max: 60
  step: 1
  mode: slider
  unit_of_measurement: seconds
  icon: mdi:pump

curatron_drying_threshold_slider:
  name: Curatron Dry Threshold
  initial: 60
  min: 20
  max: 90
  step: 1
  mode: slider
  unit_of_measurement: "%"
  icon: mdi:water-percent
  
curatron_humidity_high_threshold:
  name: Curatron High Humidity
  initial: 65
  min: 20
  max: 90
  step: 1
  mode: slider
  unit_of_measurement: "%"
  icon: mdi:water-percent-alert
  
curatron_humidity_low_threshold:
  name: Curatron Low Humidity
  initial: 55
  min: 20
  max: 90
  step: 1
  mode: slider
  unit_of_measurement: "%"
  icon: mdi:water-percent-alert

curatron_drying_start_humidity:
  name: "Drying Start Humidity"
  initial: 80
  min: 50
  max: 95
  step: 1
  mode: slider
  unit_of_measurement: "%"
  icon: mdi:water-percent
  
curatron_drying_end_humidity:
  name: "Drying End Humidity"
  initial: 60
  min: 30
  max: 80
  step: 1
  mode: slider
  unit_of_measurement: "%"
  icon: mdi:water-percent
  
curatron_drying_total_days:
  name: "Drying Total Days"
  initial: 14
  min: 3
  max: 30
  step: 1
  mode: slider
  unit_of_measurement: "days"
  icon: mdi:calendar-range
  
curatron_drying_step_days:
  name: "Days Per Step"
  initial: 2
  min: 1
  max: 7
  step: 1
  mode: slider
  unit_of_measurement: "days"
  icon: mdi:calendar-clock

curatron_drying_hysteresis:
  name: "Drying Hysteresis"
  initial: 3
  min: 1
  max: 10
  step: 1
  mode: slider
  unit_of_measurement: "%"
  icon: mdi:delta

led_strips_brightness_level:
  name: "LED Strips Brightness"
  icon: mdi:brightness-5
  min: 0
  max: 100
  step: 10
  initial: 50
  unit_of_measurement: "%"
  mode: slider
  
led_strips_color_temp:
  name: "LED Strips Color Temp"
  icon: mdi:palette
  min: 1
  max: 3
  step: 1
  initial: 2
  mode: slider

# =============================================================================
# SMART APPLIANCE POWER THRESHOLD SYSTEM
# =============================================================================

# -----------------------------------------------------------------------------
# DISHWASHER MULTI-THRESHOLD CONTROLS
# -----------------------------------------------------------------------------

dishwasher_idle_threshold:
  name: "Dishwasher Idle Threshold"
  min: 0
  max: 50
  initial: 5
  step: 1
  unit_of_measurement: "W"
  icon: mdi:dishwasher-off
  mode: slider
    
dishwasher_active_threshold:
  name: "Dishwasher Active Threshold" 
  min: 20
  max: 200
  initial: 50
  step: 5
  unit_of_measurement: "W"
  icon: mdi:dishwasher-alert
  mode: slider
    
dishwasher_peak_threshold:
  name: "Dishwasher Peak Threshold"
  min: 100
  max: 500
  initial: 150
  step: 10
  unit_of_measurement: "W"
  icon: mdi:heat-wave
  mode: slider

# -----------------------------------------------------------------------------
# WASHING MACHINE MULTI-THRESHOLD CONTROLS
# -----------------------------------------------------------------------------

washing_machine_idle_threshold:
  name: "Washing Machine Idle Threshold"
  min: 0
  max: 50
  initial: 10
  step: 1
  unit_of_measurement: "W"
  icon: mdi:washing-machine-off
  mode: slider
    
washing_machine_active_threshold:
  name: "Washing Machine Active Threshold"
  min: 50
  max: 300
  initial: 100
  step: 5
  unit_of_measurement: "W"
  icon: mdi:washing-machine-alert
  mode: slider
    
washing_machine_peak_threshold:
  name: "Washing Machine Peak Threshold"
  min: 200
  max: 800
  initial: 400
  step: 10
  unit_of_measurement: "W"
  icon: mdi:wave
  mode: slider

# -----------------------------------------------------------------------------
# LEGACY APPLIANCE CONTROLS (PRESERVED FOR BACKWARD COMPATIBILITY)
# -----------------------------------------------------------------------------

appliance_reminder_interval:
  name: "Reminder Interval (minutes)"
  min: 5
  max: 60
  step: 5
  initial: 15
  unit_of_measurement: "min"
  icon: mdi:timer

# Legacy thresholds - now replaced by multi-threshold system above
# Kept for backward compatibility with existing automations
appliance_power_threshold_dishwasher:
  name: "Dishwasher Active Power Threshold (Legacy)"
  min: 10
  max: 200
  step: 5
  initial: 50
  unit_of_measurement: "W"
  icon: mdi:flash

appliance_power_threshold_washer:
  name: "Washing Machine Active Power Threshold (Legacy)"
  min: 50
  max: 500
  step: 10
  initial: 100
  unit_of_measurement: "W"
  icon: mdi:flash

# -----------------------------------------------------------------------------
# FUTURE LEARNING SYSTEM CONTROLS (FRAMEWORK)
# -----------------------------------------------------------------------------

appliance_learning_sensitivity:
  name: "Learning Sensitivity"
  min: 1
  max: 10
  initial: 5
  step: 1
  unit_of_measurement: "level"
  icon: mdi:brain
  mode: slider

appliance_threshold_adjustment_rate:
  name: "Auto-Adjustment Rate"
  min: 0.1
  max: 2.0
  initial: 1.0
  step: 0.1
  unit_of_measurement: "factor"
  icon: mdi:tune
  mode: slider
