clean_failed_entries:
  name: Clean Failed Entries
  description: Remove failed AB BLE Gateway entries from configuration
  fields:
    dry_run:
      name: Dry Run
      description: Perform a dry run without making changes
      required: false
      default: false
      selector:
        boolean: {}

reconnect:
  name: Reconnect Gateway
  description: >
    Safely reconnect the BLE Gateway MQTT subscription.
    This service will attempt to resubscribe to the MQTT topics used by the gateway
    without requiring a Home Assistant restart.
  fields:
    entity_id:
      name: Entity ID 
      description: >
        The entity ID of the gateway to reconnect.
        Leave empty to reconnect all gateways.
        Most installations will only have one gateway.
      required: false
      example: "sensor.ble_gateway_raw_data"
      default: ""
      selector:
        text:

mqtt_reconnect:
  name: Direct MQTT Reconnect
  description: >
    Directly reconnect the BLE Gateway MQTT subscription without requiring a Home Assistant restart.
    This is a simplified version of the reconnect service that's more reliable.
  fields: {}