global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'github-actions-runner'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter (Health Monitor)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['health_monitor:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # GitHub Actions Runner (if it exposes metrics)
  - job_name: 'github-runner'
    static_configs:
      - targets: ['runner:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Docker Engine Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # Fluent Bit Metrics
  - job_name: 'fluent-bit'
    static_configs:
      - targets: ['log_aggregator:2020']
    scrape_interval: 30s
    metrics_path: /api/v1/metrics/prometheus

  # Nginx Metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_proxy:9113']
    scrape_interval: 30s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Storage configuration
storage:
  tsdb:
    retention.time: 200h
    retention.size: 10GB