global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'github-runner'
    static_configs:
      - targets: ['github-runner:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 30s
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    
  - job_name: 'fluent-bit'
    static_configs:
      - targets: ['log-aggregator:2020']
    scrape_interval: 30s