# --- Frontend (Themes & Lovelace) ---
frontend:
  themes: !include_dir_merge_named themes

# --- Lovelace Configuration ---
lovelace:
  mode: yaml
  resources:
    - url: /webrtc/webrtc-camera.js
      type: module
    - url: /local/mushroom-strategy.js
      type: module

prometheus:
  namespace: homeassistant

# --- Default Integrations ---
default_config:

# --- Configuration Splits ---
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml

# --- HTTP Configuration ---
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24

# --- Custom Panel ---
panel_custom:
  - name: ha_system
    sidebar_title: System Info
    sidebar_icon: mdi:information-variant
    js_url: /api/hassio/app/entrypoint.js
    url_path: "hassio/system/info"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

logger:
  default: info
  logs:
    custom_components.ab_gateway: debug

recorder:
  purge_keep_days: 30
