smtp:
  - name: email_kristy
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: your.email@gmail.com
    encryption: starttls
    username: your.email@gmail.com
    password: !secret gmail_app_password
    recipient: kristy.email@example.com
    sender_name: Home Assistant

# Group notifications
group:
  - name: all_devices
    services:
      - service: mobile_app_pixel_9_pro_xl
      - service: mobile_app_pixel_watch_3
  
  - name: jeremy_devices
    services:
      - service: mobile_app_pixel_9_pro_xl
      - service: mobile_app_pixel_watch_3

  - name: kristy_devices
    services:
      - service: email_kristy