
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: "welcome"
ota_password: "a44f3c1b4fdfb128c629d38403e16149"
wifi_ssid: "Lakehouse"
wifi_password: "redflower805"
ap_password: "redflower805"
api_encryption_key: "dsdH6Im7Pverxp6uu2DwyebaP/LwndSuIHM86gQ3tBo="
gmail_app_password: "klsldzcbuzkvvpwv"
mariadb_url: 'mysql://homeassistant:<PASSWORD>@core-mariadb/homeassistant?charset=utf8mb4'
