# UTC STANDARDIZED CURATRON TEMPLATE SENSORS
# File: templates_curatron_utc.yaml
# Purpose: UTC-standardized template sensors for Curatron dashboard display
# Created: June 9, 2025

template:
  - sensor:
      # === UTC STANDARDIZED CURATRON PROGRESS SENSORS ===
      - name: "Curatron Drying Progress Percentage"
        unique_id: curatron_drying_progress_percentage
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
            {% if start_timestamp > 0 %}
              {% set current_timestamp = utcnow().timestamp() %}
              {% set elapsed_hours = (current_timestamp - start_timestamp) / 3600 %}
              {% set elapsed_days = elapsed_hours / 24 %}
              {% set progress = (elapsed_days / total_days * 100) | round(1) %}
              {{ [progress, 100] | min }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "%"
        state_class: measurement
        icon: mdi:progress-clock
        attributes:
          utc_calculated: true
          last_updated_utc: "{{ utcnow().isoformat() }}Z"

      - name: "Curatron Days Elapsed"
        unique_id: curatron_days_elapsed
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% if start_timestamp > 0 %}
              {% set current_timestamp = utcnow().timestamp() %}
              {% set elapsed_hours = (current_timestamp - start_timestamp) / 3600 %}
              {{ (elapsed_hours / 24) | round(1) }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "days"
        state_class: measurement
        icon: mdi:calendar-today
        attributes:
          utc_calculated: true
          hours_elapsed: >
            {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
              {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
              {% if start_timestamp > 0 %}
                {% set current_timestamp = utcnow().timestamp() %}
                {{ ((current_timestamp - start_timestamp) / 3600) | round(1) }}
              {% else %}
                0
              {% endif %}
            {% else %}
              0
            {% endif %}

      - name: "Curatron Days Remaining"
        unique_id: curatron_days_remaining
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
            {% if start_timestamp > 0 %}
              {% set current_timestamp = utcnow().timestamp() %}
              {% set elapsed_days = (current_timestamp - start_timestamp) / 3600 / 24 %}
              {% set remaining = total_days - elapsed_days %}
              {{ [remaining, 0] | max | round(1) }}
            {% else %}
              {{ total_days }}
            {% endif %}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "days"
        state_class: measurement
        icon: mdi:calendar-clock
        attributes:
          utc_calculated: true

      # === UTC STANDARDIZED COMPLETION DATE CALCULATIONS ===
      - name: "Curatron Completion Date Local"
        unique_id: curatron_completion_date_local
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
            {% if start_timestamp > 0 %}
              {% set completion_timestamp = start_timestamp + (total_days * 24 * 3600) %}
              {{ completion_timestamp | timestamp_local }}
            {% else %}
              Unknown
            {% endif %}
          {% else %}
            Not drying
          {% endif %}
        icon: mdi:calendar-end
        attributes:
          utc_calculated: true
          completion_timestamp: >
            {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
              {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
              {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
              {% if start_timestamp > 0 %}
                {{ start_timestamp + (total_days * 24 * 3600) }}
              {% else %}
                0
              {% endif %}
            {% else %}
              0
            {% endif %}
          completion_date_utc: >
            {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
              {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
              {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
              {% if start_timestamp > 0 %}
                {% set completion_timestamp = start_timestamp + (total_days * 24 * 3600) %}
                {{ completion_timestamp | timestamp_utc }}
              {% else %}
                Unknown
              {% endif %}
            {% else %}
              Not drying
            {% endif %}

      - name: "Curatron Start Date Local"
        unique_id: curatron_start_date_local
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% if start_timestamp > 0 %}
              {{ start_timestamp | timestamp_local }}
            {% else %}
              Unknown
            {% endif %}
          {% else %}
            Not drying
          {% endif %}
        icon: mdi:calendar-start
        attributes:
          utc_calculated: true
          start_timestamp: "{{ state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) }}"
          start_date_utc: >
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% if start_timestamp > 0 %}
              {{ start_timestamp | timestamp_utc }}
            {% else %}
              Unknown
            {% endif %}

      # === UTC STANDARDIZED CURRENT STEP CALCULATION ===
      - name: "Curatron Current Drying Step"
        unique_id: curatron_current_drying_step
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% set step_days = states('input_number.curatron_drying_step_days') | float(2) %}
            {% if start_timestamp > 0 %}
              {% set current_timestamp = utcnow().timestamp() %}
              {% set elapsed_days = (current_timestamp - start_timestamp) / 3600 / 24 %}
              {{ (elapsed_days / step_days) | round(0) | int }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "step"
        state_class: measurement
        icon: mdi:stairs
        attributes:
          utc_calculated: true
          total_steps: >
            {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
            {% set step_days = states('input_number.curatron_drying_step_days') | float(2) %}
            {{ (total_days / step_days) | round(0) | int }}
          step_description: >
            {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
              {% set current_step = states('sensor.curatron_current_drying_step') | int(0) %}
              {% set total_steps = (states('input_number.curatron_drying_total_days') | float(14) / states('input_number.curatron_drying_step_days') | float(2)) | round(0) | int %}
              {% if current_step > 0 %}
                Step {{ current_step }} of {{ total_steps }}
              {% else %}
                Not started
              {% endif %}
            {% else %}
              Not drying
            {% endif %}

      # === UTC STANDARDIZED TIME REMAINING CALCULATIONS ===
      - name: "Curatron Time Remaining Display"
        unique_id: curatron_time_remaining_display
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
            {% if start_timestamp > 0 %}
              {% set current_timestamp = utcnow().timestamp() %}
              {% set elapsed_days = (current_timestamp - start_timestamp) / 3600 / 24 %}
              {% set remaining_days = total_days - elapsed_days %}
              {% if remaining_days > 1 %}
                {{ remaining_days | round(1) }} days
              {% elif remaining_days > 0 %}
                {{ (remaining_days * 24) | round(1) }} hours
              {% else %}
                Complete
              {% endif %}
            {% else %}
              Unknown
            {% endif %}
          {% else %}
            Not drying
          {% endif %}
        icon: mdi:clock-outline
        attributes:
          utc_calculated: true
          precise_hours_remaining: >
            {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
              {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
              {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
              {% if start_timestamp > 0 %}
                {% set current_timestamp = utcnow().timestamp() %}
                {% set elapsed_hours = (current_timestamp - start_timestamp) / 3600 %}
                {% set total_hours = total_days * 24 %}
                {% set remaining_hours = total_hours - elapsed_hours %}
                {{ [remaining_hours, 0] | max | round(1) }}
              {% else %}
                0
              {% endif %}
            {% else %}
              0
            {% endif %}

  - binary_sensor:
      # === UTC STANDARDIZED STATUS INDICATORS ===
      - name: "Curatron Drying Active UTC"
        unique_id: curatron_drying_active_utc
        state: >
          {{ is_state('input_boolean.curatron_drying_active_mode', 'on') }}
        device_class: running
        icon: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            mdi:fan
          {% else %}
            mdi:fan-off
          {% endif %}
        attributes:
          utc_calculated: true
          drying_since_utc: >
            {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
              {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
              {% if start_timestamp > 0 %}
                {{ start_timestamp | timestamp_utc }}
              {% else %}
                Unknown
              {% endif %}
            {% else %}
              Not drying
            {% endif %}

      - name: "Curatron Completion Soon UTC"
        unique_id: curatron_completion_soon_utc
        state: >
          {% if is_state('input_boolean.curatron_drying_active_mode', 'on') %}
            {% set start_timestamp = state_attr('input_datetime.curatron_drying_start_time', 'timestamp') | float(0) %}
            {% set total_days = states('input_number.curatron_drying_total_days') | float(14) %}
            {% if start_timestamp > 0 %}
              {% set current_timestamp = utcnow().timestamp() %}
              {% set elapsed_days = (current_timestamp - start_timestamp) / 3600 / 24 %}
              {% set remaining_days = total_days - elapsed_days %}
              {{ remaining_days <= 1 and remaining_days > 0 }}
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        device_class: timestamp
        icon: mdi:clock-alert
        attributes:
          utc_calculated: true
          warning_threshold_days: 1