version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: sae2ui4Uquah2sha7ooyieg5cheiRie6riephei9pheir4ohpeku8oal0fee4the
  client_id: Z2M
  keepalive: 60
  reject_unauthorized: false
  version: 4
serial:
  port: tcp://192.168.1.78:6638
  adapter: zstack
  baudrate: 115200
  rtscts: false
advanced:
  log_level: info
  channel: 11
  network_key:
    - 32
    - 68
    - 45
    - 239
    - 115
    - 146
    - 104
    - 18
    - 185
    - 54
    - 218
    - 131
    - 157
    - 67
    - 247
    - 199
  pan_id: 57701
  ext_pan_id:
    - 146
    - 42
    - 159
    - 146
    - 195
    - 93
    - 146
    - 83
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0xa4c138e95c788c21':
    friendly_name: bar_strip
  '0xa4c138d04ea0033c':
    friendly_name: top_left
  '0xa4c1381ee56b8bae':
    friendly_name: top_right
  '0x001788010e8b9b40':
    friendly_name: family_dimmer
groups:
  '1':
    friendly_name: all_strips
