# Secret Management Configuration for GitHub Actions Runner
# Defines encryption, storage, rotation, and access policies for secrets

secret_storage:
  # Primary storage configuration
  backend: "encrypted_file"
  
  encryption:
    algorithm: "AES-256-GCM"
    key_derivation: "scrypt"
    key_derivation_params:
      n: 32768      # CPU/memory cost parameter
      r: 8          # Block size parameter
      p: 1          # Parallelization parameter
      salt_length: 32
    
    # Master key configuration
    master_key:
      source: "file"  # file, environment, or external_kms
      location: "/home/runner/.secrets/master.key"
      permissions: "0600"
      owner: "runner:runner"
      backup_enabled: true
      backup_location: "/home/runner/.secrets/backup/"
    
    # Additional encryption layers
    envelope_encryption: true
    data_encryption_keys:
      rotation_interval_days: 30
      auto_rotation: false
      manual_approval_required: true

  # Storage locations
  storage_paths:
    secrets_directory: "/home/runner/.secrets"
    config_secrets: "/home/runner/.secrets/config"
    runtime_secrets: "/home/runner/.secrets/runtime"
    backup_secrets: "/home/runner/.secrets/backup"
    
  # File permissions
  directory_permissions: "0700"
  file_permissions: "0600"
  owner: "runner:runner"

secret_categories:
  # GitHub-related secrets
  github:
    personal_access_token:
      description: "GitHub Personal Access Token for API access"
      type: "token"
      format: "ghp_[A-Za-z0-9]{36}"
      rotation_interval_days: 30
      permissions_required:
        - "actions:read"
        - "contents:read"
        - "metadata:read"
      encryption_required: true
      audit_access: true
    
    runner_token:
      description: "GitHub Actions Runner Registration Token"
      type: "token"
      format: "[A-Z0-9]{29}"
      rotation_interval_days: 7  # Short-lived tokens
      encryption_required: true
      audit_access: true
    
    ssh_private_key:
      description: "SSH private key for Git operations"
      type: "key"
      format: "ed25519_private_key"
      rotation_interval_days: 90
      passphrase_required: true
      encryption_required: true
      audit_access: true

  # Infrastructure secrets
  infrastructure:
    docker_registry_credentials:
      description: "Docker registry authentication"
      type: "credentials"
      rotation_interval_days: 60
      encryption_required: true
      audit_access: true
    
    monitoring_api_keys:
      description: "Monitoring service API keys"
      type: "api_key"
      rotation_interval_days: 45
      encryption_required: true
      audit_access: true

  # Backup and recovery
  backup:
    encryption_keys:
      description: "Backup encryption keys"
      type: "key"
      rotation_interval_days: 180
      encryption_required: true
      audit_access: true
      
    recovery_codes:
      description: "Emergency recovery codes"
      type: "recovery_code"
      rotation_interval_days: 365
      encryption_required: true
      audit_access: true

rotation_policies:
  # Automatic rotation configuration
  automatic_rotation:
    enabled: false  # Manual approval required for production
    schedule: "0 2 * * 0"  # Weekly on Sunday at 2 AM
    advance_warning_days: 7
    
  # Manual rotation process
  manual_rotation:
    approval_required: true
    approver_roles: ["admin", "security_team"]
    documentation_required: true
    testing_required: true
    
  # Emergency rotation
  emergency_rotation:
    enabled: true
    immediate_execution: true
    notification_required: true
    audit_trail_required: true
    
  # Rotation workflow
  rotation_workflow:
    pre_rotation_checks:
      - validate_new_secret
      - check_dependencies
      - create_backup
      - notify_stakeholders
    
    rotation_steps:
      - generate_new_secret
      - test_new_secret
      - update_configurations
      - restart_services
      - validate_functionality
    
    post_rotation_checks:
      - verify_service_health
      - confirm_old_secret_revoked
      - update_documentation
      - send_completion_notification

access_control:
  # Secret access patterns
  access_patterns:
    runtime_access:
      method: "environment_variable"
      encryption_at_rest: true
      encryption_in_transit: true
      temporary_access: true
      session_bound: true
    
    configuration_access:
      method: "file_based"
      encryption_at_rest: true
      file_permissions: "0600"
      owner_restricted: true
      audit_required: true
    
    administrative_access:
      method: "direct_file"
      encryption_at_rest: true
      multi_factor_required: true
      approval_required: true
      audit_required: true

  # Access restrictions
  restrictions:
    time_based_access:
      enabled: false  # 24/7 runner operation
      allowed_hours: "00:00-23:59"
      timezone: "UTC"
    
    ip_restrictions:
      enabled: false  # Container networking handles this
      allowed_cidrs: []
    
    process_restrictions:
      allowed_processes:
        - "github-runner"
        - "git"
        - "docker"
        - "node"
        - "python"
      forbidden_processes:
        - "nc"
        - "netcat"
        - "telnet"
        - "ftp"

  # Secret injection methods
  injection_methods:
    environment_variables:
      enabled: true
      prefix: "GITHUB_RUNNER_"
      secure_handling: true
      clear_after_use: true
    
    configuration_files:
      enabled: true
      template_based: true
      runtime_generation: true
      cleanup_after_use: true
    
    volume_mounts:
      enabled: true
      read_only: true
      temporary_mounts: true
      secure_permissions: true

backup_and_recovery:
  # Backup configuration
  backup:
    enabled: true
    schedule: "0 3 * * *"  # Daily at 3 AM
    retention_days: 90
    
    encryption:
      enabled: true
      separate_key: true
      key_escrow: true
    
    storage:
      local_backup: true
      remote_backup: false  # Configure for production
      verification_required: true
    
    compression:
      enabled: true
      algorithm: "gzip"
      compression_level: 6

  # Recovery procedures
  recovery:
    automated_recovery: false
    manual_approval_required: true
    testing_required: true
    
    recovery_methods:
      - master_key_recovery
      - individual_secret_recovery
      - full_system_recovery
    
    recovery_validation:
      - secret_integrity_check
      - access_pattern_validation
      - service_functionality_test

monitoring:
  # Secret access monitoring
  access_monitoring:
    enabled: true
    log_level: "info"
    real_time_alerts: true
    
    events_to_monitor:
      - secret_access_attempts
      - secret_decryption_events
      - secret_rotation_events
      - unauthorized_access_attempts
      - secret_integrity_violations
    
    alerting:
      webhook_url: "${SECURITY_WEBHOOK_URL}"
      severity_threshold: "medium"
      rate_limiting: "10/minute"

  # Integrity monitoring
  integrity_monitoring:
    enabled: true
    check_interval: "1h"
    
    checks:
      - file_integrity_verification
      - encryption_key_validation
      - access_permission_audit
      - secret_expiry_check
    
    failure_actions:
      - immediate_alert
      - access_restriction
      - audit_log_entry
      - emergency_rotation_trigger

compliance:
  # Compliance frameworks
  frameworks:
    pci_dss:
      enabled: false
      requirements:
        - encrypt_secrets_at_rest
        - encrypt_secrets_in_transit
        - regular_key_rotation
        - access_logging
    
    hipaa:
      enabled: false
      requirements:
        - encryption_standards
        - access_controls
        - audit_trails
        - data_retention
    
    gdpr:
      enabled: false
      requirements:
        - data_protection
        - access_rights
        - deletion_capabilities
        - consent_management

  # Security standards
  security_standards:
    fips_140_2:
      enabled: false
      level: "Level 2"
    
    common_criteria:
      enabled: false
      evaluation_assurance_level: "EAL4"

audit:
  # Audit configuration
  audit_logging:
    enabled: true
    log_format: "json"
    log_rotation:
      max_size: "100MB"
      max_files: 10
      max_age: "365d"
    
    audit_events:
      - secret_creation
      - secret_access
      - secret_modification
      - secret_deletion
      - secret_rotation
      - access_denied
      - integrity_failures
      - configuration_changes
    
    sensitive_data_handling:
      mask_secret_values: true
      hash_identifiers: true
      truncate_large_values: true

  # Compliance reporting
  reporting:
    enabled: true
    formats: ["json", "csv", "pdf"]
    schedule: "weekly"
    retention_days: 2555  # 7 years
    
    reports:
      - secret_inventory
      - access_summary
      - rotation_status
      - compliance_gaps
      - security_incidents