# =============================================================================
# HOME ASSISTANT DEVELOPMENT ENVIRONMENT SECRETS
# =============================================================================
# This file contains development-safe secrets for the Docker dev environment
# DO NOT use production secrets in development!

# Development Database (uses SQLite in container)
db_url: sqlite:////config/home-assistant_v2.db

# Development HTTP settings
http_server_host: 0.0.0.0
http_server_port: 8123
http_base_url: http://localhost:8124

# Development API tokens (non-functional placeholders)
hass_token: dev-token-placeholder-not-real
adaptive_lighting_token: dev-adaptive-lighting-token

# Development integrations (disabled/mocked)
# These should be disabled or use mock values in development
weather_api_key: dev-weather-api-key-placeholder
bluetooth_adapter: disabled-in-dev
zwave_device: disabled-in-dev

# Development notification settings
notify_dev: true
email_dev: dev-notifications-disabled

# Development device placeholders
dev_mode: true
production_mode: false

# Placeholder credentials for integrations that require them
# These won't work but prevent errors during startup
mqtt_username: dev-mqtt-user
mqtt_password: dev-mqtt-pass
wifi_ssid: dev-wifi-network
wifi_password: dev-wifi-pass

# Development Z-Wave settings (disabled)
zwave_network_key: "0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00"

# Development sensor overrides
# Use mock values for sensors that won't exist in dev environment
sensor_override_mode: true
mock_sensors: true